### ISSUE TITLE
brave fails to start on ubuntu 18.10

### ISSUE THREAD

**Issue by lucasdavila86** [bbc/brave#15]
After installing all the dependencies on ubuntu 18.10 I was unable to start brave. This error shows up:
Missing gstreamer plugins: ['faac']

I was reading about the ubuntu packages and seems they dropped the faac support on the gstreamer bad plugins, maybe in favor of avenc_aac, avdec_aac (these ones are supported, see below)

```
gst-inspect-1.0 | grep aac
libav:  avenc_aac: libav AAC (Advanced Audio Coding) encoder
libav:  avdec_aac: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_fixed: libav AAC (Advanced Audio Coding) decoder
libav:  avdec_aac_latm: libav AAC LATM (Advanced Audio Coding LATM syntax) decoder
libav:  avmux_adts: libav ADTS AAC (Advanced Audio Coding) muxer (not recommended, use aacparse instead)
audioparsers:  aacparse: AAC audio stream parser
typefindfunctions: audio/aac: aac, adts, adif, loas
voaacenc:  voaacenc: AAC audio encoder
```

**Comment by matthew1000** [comment]
Thanks @lucasdavila86 good spot. 

I did a search and replace on faac --> avenc_aac but the pipeline failed so it'll need a bit further digging. I'll get on it.

**Comment by lucasdavila86** [comment]
Found a bug report about 'faac' support on gst-plugins-bad. It's quite old, ~2014
https://bugs.launchpad.net/ubuntu/+source/gst-plugins-bad1.0/+bug/1299376

**Comment by matthew1000** [comment]
OK, we have a pull request https://github.com/bbc/brave/pull/17 to remove all `faac` usage... which can now go in to master.

**Comment by moschopsuk** [comment]
@lucasdavila86 I'm going to close this issue, please feel to reopen if this is still an issue.
