### ISSUE TITLE
QUIC support ?

### ISSUE THREAD

**Issue by gedw99** [bbc/brave#21]
SRT versus QUIC...

Wondering if QUIC is on your radar as SRT seems to not support CMAF and so will probably die a slow death.

**Comment by nitrat7** [comment]
SRT is perfect for contribution - I don’t see any big potential for distribution.

**Comment by moschopsuk** [comment]
Could you please elaborate  on your question @gedw99.

Would this be for contribution? Or distribution?

**Comment by moschopsuk** [comment]
Closing issue due to no further responses.
