### ISSUE TITLE
mixer wrong dimension and green

### ISSUE THREAD

**Issue by hjanuschka** [bbc/brave#53]
hey 🤚  great project!! ❤️ 

having the following problem.
when i have a couple of sources (uri, mp4) - and i `cut_to_source` them on the mixer1
on the first run it looks like:
(wrong color, and i think it is the wrong dimensions)

![Bildschirmfoto 2019-10-28 um 10 34 45](https://user-images.githubusercontent.com/2891702/67669207-b718fe80-f971-11e9-9a93-6d8a5c9a3a40.png)

clicking on the `eye`  deleting it from the mixer, and `cut_to_source` again, fixes it
![Bildschirmfoto 2019-10-28 um 10 57 42](https://user-images.githubusercontent.com/2891702/67669251-cdbf5580-f971-11e9-8679-61fe1920b67b.png)

if i add an output directly to the source, it is stable/normal from the beginning. so i suspect some problem in the mixer, do you have any idea, where i could start looking at?

**Comment by hjanuschka** [comment]
once all sources have been toggled atleast once, the `cut_to_source` works flawless 👍

**Comment by moschopsuk** [comment]
Hello  @hjanuschka.

We've not seen any issue like this before. What type of uri sources have you been testing with?

I'm not a 100% sure but it could be some issues with the caps not being parsed correctly by underlying gstreamer.

**Comment by hjanuschka** [comment]
it seemed to be a issue with gst 1.17-HEAD - rolled back to 1.16 and it was working.
