### ISSUE TITLE
"GStreamer error: clock problem." when changing base resolution

### ISSUE THREAD

**Issue by dromer** [bbc/brave#61]
My input and mixer objects are both ```1280x720```, but when I add an output stream it will automatically take the default resolution of ```640x360``` instead of it's source object.

So I changed the default width and height in my configuration, but then the output object (to rtmp) breaks with:
```GStreamer error: clock problem.```

This happens with both gstreamer 1.14.x and 1.16.x

The same error occurs when setting the resolution on the output object directly.

**Comment by dromer** [comment]
When I set the resolution to ie. 848x480 I get: 
```Pipeline construction is invalid, please add queues.```

Has anyone tested this with outputs other than ```640x360``` ?

**Comment by matthew1000** [comment]
I definitely got it working with 720p ... you may have found a bug though.

**Comment by dromer** [comment]
I tried with different base images. 19.04 and 19.10 (the later has gstreamer 1.16.x)
Same result.

I have a very simple pipeline. I open a 720p rtmp input. have a mixer object at 720p and then start an rtmp output, which by default runs at 640x360

**Comment by dromer** [comment]
Btw here the full console output for posterity:
```
bbc-brave_1  |  WARNING: [   output1] GStreamer warning from mux: gst-core-error-quark: GStreamer error: clock problem. (13)
bbc-brave_1  |  WARNING: [   output1] GStreamer warning debug: gstaggregator.c(1780): gst_aggregator_query_latency_unlocked (): /GstPipeline:pipeline1/GstFlvMux:mux:
bbc-brave_1  | Impossible to configure latency: max 0:00:02.000000000 < min 0:00:02.066666667. Add queues or other buffering elements.
bbc-brave_1  |  WARNING: [   output1] GStreamer warning message: GStreamer error: clock problem.
```

**Comment by dromer** [comment]
I played a bit with this fork and so far it seems quite excellent: https://github.com/bitwave-tv/brave
(at least 720p seems to work fine. WebRTC still doesn't work for me but that's ok)

**Comment by dromer** [comment]
Has this been fixed?

**Comment by nikell28** [comment]
@moschopsuk  This problem have decision?

**Comment by nikell28** [comment]
@dromer, hello!
Were you able to find a solution?
Help me please!

**Comment by dromer** [comment]
use the fork: https://github.com/bitwave-tv/brave

That worked for me.

(I haven't played with this since, so can't help you any more than this)

**Comment by nikell28** [comment]
> use the fork: https://github.com/bitwave-tv/brave
> 
> That worked for me.
> 
> (I haven't played with this since, so can't help you any more than this)

I tried to run this fork yesterday
It didn't work for me

But this option worked
Here in this line:
https://github.com/bbc/brave/blob/master/brave/outputs/output.py#L174
Add "queue" like that 

`return 'interaudiosrc name=interaudiosrc ! audioconvert ! audioresample !  queue ! '`
