### ISSUE TITLE
Unable to setup brave on Ubuntu 20.04

### ISSUE THREAD

**Issue by anindoghosh** [bbc/brave#73]
I am trying to setup brave on a ubuntu 20.04 virtual machine. I am unable to install the _python-gst-1.0_. I tried by installing **python3-gst-1.0** instead but when I run pipenv install it gives an error:
An error occurred while installing pillow==6.2.0
Any idea what should be done in order to fix this issue and install brave successfully?

**Comment by shane-edmonds** [comment]
I had to make sure libjpeg was installed and updated before pillow would install for me. ymmv

**Comment by anindoghosh** [comment]
Thanks for the reply. I installed libjpeg and now everything works fine.
